program: src/sweeps/train_wrapper.py
method: bayes
metric:
  name: valid/loss
  goal: minimize
parameters:
  model.encoder.depth:
    values: [4, 5]
  model.encoder.width:
    values: [256, 512, 1024]
  model.value_decoder.depth:
    values: [4, 5]
  model.value_decoder.width:
    values: [256, 512, 1024]
  model.z_size:
    values: [128]
  training.batch_size:
    values: [1024]
  training.optimizer.lr:
    values: [1e-4]
  training.criterion.kl_weight:
    values: [1e-2, 1e-3, 1e-4]
  training.sampling.eps:
    values: [0, 1e-6, 1e-4, 1e-2]
