model:
  encoder:
    size_hidden: 256
    architecture: residual-parameterized
    depth: 3
    width: 1024
  z_size: 256
  decoder:
    z_slice: [0, -1]
    size_hidden: 128
    architecture: mlp-parameterized
    depth: 10
    width: 128
  value_decoder:
    z_slice: [0, -1]
    architecture: residual-parameterized
    depth: 3
    width: 1024
  io_format:
    seq_len: 15
    token_cnt: 10
    val_points: 100

training:
  batch_size: 1024
  epochs: 100
  valid_split: 0.1
  dataset_len_limit: null
  mode: value_prediction  # value_prediction, autoencoding or mixed
  criterion:
    ae_weight: 0
    kl_weight: 1e-4
    syntax_weight: 0.5
    contrastive_weight: 0
  sampling:
    prior_std: 1
    eps: 0
  optimizer:
    lr: 1e-3
    clip: 1
    scheduler_factor: 0.1
    scheduler_patience: 10
    scheduler_threshold: 2e-4
    scheduler_min_lr: 0
  performance_metric: valid/loss
  kl_anneal:
    schedule: sigmoid
    midpoint: 0.4
    steepness: 15
  values_init_bias: false
  use_grammar_mask: false
