# Optuna Hyperparameter Optimization Configuration - Neural Backend Parameters
# Phase 1: Optimize neural mutation backend settings with fixed mutation weights

# Study settings
study:
  name: "optim_neural_1"
  direction: "maximize"
  storage: "sqlite:///sweeps/optuna_neural_study.db"

# Sampler configuration for noisy objectives
sampler:
  type: "TPESampler"
  n_startup_trials: 20  # Reduced for smaller parameter space
  n_ei_candidates: 24
  multivariate: true    # Consider parameter interactions

# Pruner configuration - conservative for noisy objectives
pruner:
  type: "MedianPruner"
  n_startup_trials: 10      # Fewer startup trials for 8D space
  n_warmup_steps: 20        # Wait for 20 equations before pruning
  interval_steps: 10        # Only check every 10 equations

# Execution settings
execution:
  n_trials: 100                     # Focused trials for neural params only
  equations_per_batch: 5          # Report intermediate results every N equations

# Dataset and run configuration
dataset:
  name: "pysr-univariate"          # Dataset to use
  equation_indices: "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,29,30,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,79,80,81,83,84,85,86,87,88,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106"
  num_samples: 2000                # Samples per equation
  noise: 0.0001                    # Relative noise magnitude
  n_runs: 5                        # Reduced runs for faster iteration

# Base configuration file to use for non-optimized parameters
base_config: "run/config_neural.yaml"

# Hyperparameter search space - Neural options only
hyperparameters:

  # Neural options - the parameters we want to optimize
  neural_options:
    sampling_eps:
      type: "float"
      low: 0.005
      high: 0.15
      log: false

    subtree_min_nodes:
      type: "int"
      low: 3
      high: 8

    subtree_max_nodes_diff:
      type: "int"
      low: 2
      high: 6

    max_tree_size_diff:
      type: "int"
      low: 0
      high: 10

    require_tree_size_similarity:
      type: "categorical"
      choices: [true, false]

    require_novel_skeleton:
      type: "categorical"
      choices: [true, false]

    require_expr_similarity:
      type: "categorical"
      choices: [true, false]

    similarity_threshold:
      type: "float"
      low: 0.0
      high: 1.5

    max_resamples:
      type: "categorical"
      choices: [31, 63, 127]
