run_settings:
  verbosity: 0
  n_runs: 2
  max_iter: 10  # Reduced for testing
  early_stopping_condition: 1e-8
  log_dir: /cephfs/store/gr-mc2473/lc865/workspace/benchmark_data/sept-test
  wandb_logging: true

dataset:
  name: pysr-difficult
  num_samples: 2000  # Same settings as full1_
  noise: 0
  equation_indices: [102, 202]  # Two equations for minimal testing
  forbid_ops: []
  univariate: true

symbolic_regression:
  neural_options:
    active: false  # Disabled for vanilla mode
    model_path: /cephfs/home/lc865/workspace/similar-expressions/onnx-models/model-e51hcsb9.onnx
    sampling_eps: 0.02
    subtree_min_nodes: 2
    subtree_max_nodes: 14
    device: cuda
    verbose: true
    max_tree_size_diff: 8
    require_tree_size_similarity: true
    require_novel_skeleton: true
    require_expr_similarity: true
    similarity_threshold: 0.2  # Using double actual similarity_threshold to speed up computation
    log_subtree_strings: false
    sample_logits: true
    max_resamples: 127
    sample_batchsize: 32
    subtree_max_features: 2

  mutation_weights:
    weight_add_node: 2.47
    weight_insert_node: 0.0112
    weight_delete_node: 0.870
    weight_do_nothing: 0.273
    weight_mutate_constant: 0.0346
    weight_mutate_operator: 0.293
    weight_swap_operands: 0.198
    weight_rotate_tree: 4.26
    weight_randomize: 0.000502
    weight_simplify: 0.00209
    weight_optimize: 0.0
    weight_neural_mutate_tree: 0.0  # Disabled for vanilla mode