run_settings:
  n_runs: 6
  max_iter: 20
  early_stopping_condition: 1e-8
  log_dir: /cephfs/store/gr-mc2473/lc865/workspace/benchmark_data/sept-baseline-3-vanilla

  run_prefix: feynmanMultivariate
  do_vanilla: true
  do_neural: false

dataset:
  name: pysr-difficult
  num_samples: 2000  # Same settings as full1_
  noise: 0
  equation_indices: [ 102,  202,  302,  402,  502,  602,  702,  802,  902, 1002, 1102,
       1202, 1302, 1402, 1502, 1602, 1702, 1802, 1902, 2002, 2102, 2202,
       2302, 2402, 2502, 2602, 2702, 2802, 2902, 3002,
       103,  203,  303,  403,  503,  603,  703,  803,  903, 1003, 1103,
       1203, 1303, 1403, 1503, 1603, 1703, 1803, 1903, 2003, 2103, 2203,
       2303, 2403, 2503, 2603, 2703, 2803, 2903, 3003]
  forbid_ops: []
  univariate: true

symbolic_regression:
  neural_options:
    active: false  # Disabled for vanilla mode
    model_path: /cephfs/home/lc865/workspace/similar-expressions/onnx-models/model-e51hcsb9.onnx
    sampling_eps: 0.02
    subtree_min_nodes: 2
    subtree_max_nodes: 14
    device: cuda
    verbose: true
    max_tree_size_diff: 8
    require_tree_size_similarity: true
    require_novel_skeleton: true
    require_expr_similarity: true
    similarity_threshold: 0.2  # Using double actual similarity_threshold to speed up computation
    log_subtree_strings: false
    sample_logits: true
    max_resamples: 127
    sample_batchsize: 32
    subtree_max_features: 2

  mutation_weights:
    weight_add_node: 2.47
    weight_insert_node: 0.0112
    weight_delete_node: 0.870
    weight_do_nothing: 0.273
    weight_mutate_constant: 0.0346
    weight_mutate_operator: 0.293
    weight_swap_operands: 0.198
    weight_rotate_tree: 4.26
    weight_randomize: 0.000502
    weight_simplify: 0.00209
    weight_optimize: 0.0
    weight_neural_mutate_tree: 0.0  # Disabled for vanilla mode