wandb_version: 1

encoder_hidden:
  desc: null
  value: 128
z_size:
  desc: null
  value: 128
decoder_hidden:
  desc: null
  value: 64
rnn_type:
  desc: null
  value: lstm
batch_size:
  desc: null
  value: 128
seq_len:
  desc: null
  value: 15
token_cnt:
  desc: null
  value: 10
val_points:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.002
clip:
  desc: null
  value: 5.0
print_every:
  desc: null
  value: 200
epochs:
  desc: null
  value: 100
value_loss_weight:
  desc: null
  value: 3
const_loss_weight:
  desc: null
  value: 1
syntax_loss_weight:
  desc: null
  value: 1
device:
  desc: null
  value: cpu
conv_size:
  desc: null
  value: large
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1724156327
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.17.7
      8:
      - 1
      - 5
      - 12
      13: linux-x86_64
