wandb_version: 1

learning_rate:
  desc: null
  value: 0.004
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 32
value_loss_weight:
  desc: null
  value: 0
const_loss_weight:
  desc: null
  value: 1
encoder_hidden:
  desc: null
  value: 20
z_size:
  desc: null
  value: 4
decoder_hidden:
  desc: null
  value: 20
rnn_type:
  desc: null
  value: lstm
val_points:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723935365
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.12.4
      5: 0.17.7
      8:
      - 4
      - 5
      13: darwin-arm64
