program: src/sweeps/train_wrapper.py
method: random
metric:
  name: valid/loss
  goal: minimize
parameters:
  model.encoder.depth:
    values: [2, 3, 4]
  model.encoder.width:
    values: [256, 512, 1024]
  model.value_decoder.depth:
    values: [2, 3]
  model.value_decoder.width:
    values: [256, 512, 1024]
  model.decoder.depth:
    values: [2, 3]
  model.decoder.width:
    values: [256, 512, 1024]
  training.batch_size:
    values: [128, 256, 512]
  